[build]
  command = "pip install -r requirements.txt && streamlit run app/portfolio.py --server.headless=true --server.port=8501"
  publish = "dist"

[build.environment]
  PYTHON_VERSION = "3.9"

[[redirects]]
  from = "/*"
  to = "/"
  status = 200