# Streamlit configuration

[server]
headless = true
enableCORS = false
enableXsrfProtection = false
maxUploadSize = 5
port = 8501

[browser]
gatherUsageStats = false

[theme]
primaryColor = "#00FF41"
backgroundColor = "#101010"
secondaryBackgroundColor = "#0D1F0C"
textColor = "#C8FFC8"