[server]
headless = true
enableCORS = false
enableXsrfProtection = false
maxUploadSize = 1028

[theme]
primaryColor = "#8B5CF6"
backgroundColor = "#0d1117"
secondaryBackgroundColor = "#161b22"
textColor = "#f0f6fc"

[browser]
gatherUsageStats = false

[logger]
level = "info"