[server]
headless = true
port = 8501
address = "0.0.0.0"
enableCORS = false
enableXsrfProtection = false

[theme]
primaryColor = "#8B5CF6"
backgroundColor = "#0d1117"
secondaryBackgroundColor = "#161b22"
textColor = "#f0f6fc"

[browser]
gatherUsageStats = false